modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = "https://github.com/NinjaPhenix/ExpandedStorage/issues/"
license = "All Rights Reserved"

[[mods]]
modId = "expandedstorage"
version = "${version}"
displayName = "Expanded Storage"
authors = "NinjaPhenix"
logoFile = "icon.png"

[[dependencies.expandedstorage]]
modId = "forge"
mandatory = true
versionRange = "[35.1.37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.expandedstorage]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4,)"
ordering = "NONE"
side = "BOTH"
